QuizSystem/Controllers/EditController.cs
using BLL.Dto;
using BLL.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace QuizSystem.Controllers
{
    [Authorize(Roles = "SuperAdmin, Admin")]
    public class EditController : Controller
    {
        private readonly IQuizService _quizService;
        private readonly IQuestionService _questionService;
        public EditController(IQuizService quizService, IQuestionService questionService)
        {
            _quizService = quizService;
            _questionService = questionService;
        }

        [HttpGet]
        public async Task<ActionResult> Quiz(int? id)
        {
            if (id == null)
            {
                return View("EditQuiz");
            }
            var q = await _quizService.GetByIdAsync(id.GetValueOrDefault());

            return View("EditQuiz", q);
        }

        [HttpGet]
        public async Task<ActionResult> Question(int? id, int? quiz)
        {
            if (id == null)
            {
                if (quiz == null)
                {
                    return RedirectToAction("Quiz");
                }
                ViewBag.QuizId = quiz;
                return View("EditQuestion");
            }
            var q = await _questionService.GetByIdAsync(id.GetValueOrDefault());
            if (q == null)
            {
                return RedirectToAction("Quiz");
            }

            return View("EditQuestion", q);
        }
        [HttpGet]
        public async Task<ActionResult> Answer(int? id, int? question)
        {
            if (id == null)
            {
                if (question == null)
                {
                    return RedirectToAction("Quiz");
                }
                ViewBag.QuestionId = question;
                return View("EditAnswer");
            }
            var answer = await _questionService.GetAnswerByIdAsync(id.GetValueOrDefault());
            if (answer == null)
            {
                return RedirectToAction("Quiz");
            }

            return View("EditAnswer", answer);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateQuiz(QuizDTO quizDTO)
        {
            try
            {
                await _quizService.UpdateAsync(quizDTO);

                return RedirectToAction("Quiz", new { id = quizDTO.Id });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("EditQuiz", quizDTO);
            }
        }

        [HttpPost]
        public async Task<ActionResult> CreateQuiz(QuizDTO quizDTO)
        {
            try
            {
                await _quizService.CreateAsync(quizDTO);

                return RedirectToAction("Quiz", new { id = quizDTO.Id });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("EditQuiz", quizDTO);
            }
        }

        [HttpPost]
        public async Task<ActionResult> DeleteQuiz(int? id)
        {
            var successful = await _quizService.DeleteAsync(id.GetValueOrDefault());
            if (successful)
                return RedirectToAction("Quiz");
            else
            {
                Response.StatusCode = 400;
                return Json("fail");
            }               
        }

        [HttpPost]
        public async Task<ActionResult> CreateQuestion(QuestionDTO questionDTO)
        {
            try
            {
                await _questionService.CreateAsync(questionDTO);

                return RedirectToAction("Question", new { id = questionDTO.Id });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("EditQuestion", questionDTO);
            }
        }
        [HttpPost]
        public async Task<ActionResult> UpdateQuestion(QuestionDTO questionDTO)
        {
            try
            {
                await _questionService.UpdateAsync(questionDTO);

                return RedirectToAction("Question", new { id = questionDTO.Id });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("EditQuestion", questionDTO);
            }
        }

        [HttpPost]
        public async Task<ActionResult> DeleteQuestion(int? id)
        {
            var successful = await _questionService.DeleteAsync(id.GetValueOrDefault());
            if (successful>0)
                return RedirectToAction("Quiz", new { id = successful });
            else
            {
                Response.StatusCode = 400;
                return Json("fail");
            }
        }

        [HttpPost]
        public async Task<ActionResult> CreateAnswer(AnswerDTO answerDTO)
        {
            try
            {
                await _questionService.AddAnswerAsync(answerDTO);

                return RedirectToAction("Question", new { id = answerDTO.QuestionId });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("EditAnswer", answerDTO);
            }
        }
        [HttpPost]
        public async Task<ActionResult> UpdateAnswer(AnswerDTO answerDTO)
        {
            try
            {
                await _questionService.UpdateAnswerAsync(answerDTO);

                return RedirectToAction("Question", new { id = answerDTO.QuestionId });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("EditAnswer", answerDTO);
            }
        }
        [HttpPost]
        public async Task<ActionResult> DeleteAnswer(int? id)
        {
            var successful = await _questionService.DeleteAnswerAsync(id.GetValueOrDefault());
            if (successful>0)
                return RedirectToAction("Question", new { id = successful });
            else
            {
                Response.StatusCode = 400;
                return Json("fail");
            }
        }
    }
}

QuizSystem/Views/Edit/EditAnswer.cshtml
@model BLL.Dto.AnswerDTO
@{
    ViewBag.Title = "EditAnswer";
    ViewBag.IsEdit = Model != null && Model.Id != 0;
    ViewBag.Act = ViewBag.IsEdit ? "UpdateAnswer" : "CreateAnswer";

    ViewBag.QuestionId = ViewBag.IsEdit ? Model.QuestionId : ViewBag.QuestionId;
}

<h4>Answer CRUD</h4>
<hr />
<div class="row">
    <div class="col-12">
        <div class="text-center">
            <a href="/Edit/Question/@ViewBag.QuestionId">вернуться к вопросу</a>
            <hr />
        </div>
    </div>
    <div class="col">
        @using (Html.BeginForm((string)ViewBag.Act, "Edit"))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            @Html.Hidden("QuestionId", (int)ViewBag.QuestionId)

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsCorrect, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsCorrect)
                            @Html.ValidationMessageFor(model => model.IsCorrect, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @if (ViewBag.IsEdit)
                        {
                            <input type="submit" value="Update" class="btn btn-primary" />
                        }
                        else
                        {
                            <input type="submit" value="Create" class="btn btn-primary" />
                        }
                    </div>
                </div>
            </div>
        }
        @if (ViewBag.IsEdit)
        {
            using (Html.BeginForm("DeleteAnswer", "Edit"))
            {
                @Html.HiddenFor(model => model.Id)
                <input type="submit" value="Delete" class="btn btn-danger btn-sm" />
            }
        }
    </div>
</div>

QuizSystem/Views/Edit/EditQuestion.cshtml
@model BLL.Dto.QuestionDTO
@{
    ViewBag.Title = "EditQuestion";
    ViewBag.IsEdit = Model != null && Model.Id != 0;
    ViewBag.Act = ViewBag.IsEdit ? "UpdateQuestion" : "CreateQuestion";

    ViewBag.QuizId = ViewBag.IsEdit ? Model.QuizId : ViewBag.QuizId;
}

<h4>Question CRUD</h4>
<hr />
<div class="row">
    <div class="col-12">
        <div class="text-center">
            <a href="/Edit/Quiz/@ViewBag.QuizId">вернуться к тесту</a>
            <hr />
        </div>
    </div>
    <div class="col">
        @using (Html.BeginForm((string)ViewBag.Act, "Edit"))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            @Html.Hidden("QuizId", (int)ViewBag.QuizId)

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @if (ViewBag.IsEdit)
                        {
                            <input type="submit" value="Update" class="btn btn-primary" />
                        }
                        else
                        {
                            <input type="submit" value="Create" class="btn btn-primary" />
                        }
                    </div>
                </div>
            </div>
        }
        @if (ViewBag.IsEdit)
        {
            using (Html.BeginForm("DeleteQuestion", "Edit"))
            {
                @Html.HiddenFor(model => model.Id)
                <input type="submit" value="Delete" class="btn btn-danger btn-sm" />
            }
        }
    </div>
    @if (ViewBag.IsEdit)
    {
    <div class="col">
        <p class="font-weight-bold">Ответы.&nbsp;&nbsp;
        <a href="/Edit/Answer?question=@Model.Id" class="badge badge-primary">Добавить ответ</a></p>
        <ul class="list-group">
            @foreach (var item in Model.Answers)
            {
            <li class="list-group-item">
                <a class="card-link small" href="/Edit/Answer/@item.Id">Редактировать</a>
                &nbsp;
                <span class="font-italic">@item.IsCorrect</span>&nbsp;&mdash;&nbsp;&nbsp;@item.Text
            </li>
            }
        </ul>
    </div>
    }

</div>

QuizSystem/Views/Edit/EditQuiz.cshtml
@model BLL.Dto.QuizDTO
@{
    ViewBag.Title = "EditQuiz";
    ViewBag.IsEdit = Model != null && Model.Id != 0;
    ViewBag.Act = ViewBag.IsEdit ? "UpdateQuiz" : "CreateQuiz";
}

<h3>Quiz CRUD</h3>
<hr />

<div class="row">
    <div class="col">
        @using (Html.BeginForm((string)ViewBag.Act, "Edit"))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            <div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TimeToTest, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TimeToTest, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TimeToTest, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @if (ViewBag.IsEdit)
                        {
                            <input type="submit" value="Update" class="btn btn-primary" />
                        }
                        else
                        {
                            <input type="submit" value="Create" class="btn btn-primary" />
                        }

                    </div>
                </div>
            </div>
        }
        @if (ViewBag.IsEdit)
        {
            using (Html.BeginForm("DeleteQuiz", "Edit"))
            {
                @Html.HiddenFor(model => model.Id)
                <input type="submit" value="Delete" class="btn btn-danger btn-sm" />
            }
        }
    </div>
    @if (ViewBag.IsEdit)
    {
        <div class="col">
            <p class="font-weight-bold">Вопросы.&nbsp;&nbsp;<a href="/Edit/Question?quiz=@Model.Id" class="badge badge-primary">Добавить вопрос</a></p>
            <div class="accordion" id="accordionExample">
                @foreach (var item in Model.Questions)
                {
                    <div class="card">
                        <div class="card-header">
                            <button class="btn text-left" data-toggle="collapse" data-target="@(String.Format("#collapse{0}", item.Id))">
                                @item.Text
                            </button>
                            <a class="card-link small" href="/Edit/Question/@item.Id">Редактировать</a>
                        </div>
                        <div id="@(String.Format("collapse{0}", item.Id))" class="collapse" data-parent="#accordionExample">
                            <div class="card-body">
                                <ul>
                                    @foreach (var answ in item.Answers)
                                    {
                                        <li>@answ.Text - @answ.IsCorrect</li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    }
</div>