QuizSystem/Controllers/QuizController.cs
using BLL.Dto;
using BLL.Services;
using QuizSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace QuizSystem.Controllers
{
    [Authorize]
    public class QuizController : Controller
    {
        private readonly IQuizService _quizService;
        public QuizController(IQuizService quizService)
        {
            _quizService = quizService;
        }

        [HttpGet]
        public async Task<ActionResult> Quizzes(string q = null, int page = 1)
        {
            int pageSize = 3; // количество объектов на страницу
            var list = await _quizService.GetAsync((page - 1) * pageSize, pageSize, q);

            var totalCount = list.Count() > 0 ? list.FirstOrDefault().TotalCount : 0;
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = totalCount };
            QuizzesViewModel qvm = new QuizzesViewModel { PageInfo = pageInfo, Quizzes = list };

            return View(qvm);
        }

        [HttpGet]
        [Util.Filters.IfWrongParameter(Redir = "/Quiz/Quizzes")]
        public async Task<ActionResult> QuizPage(int? id)
        {
            var quiz = await _quizService.GetByIdAsync(id.GetValueOrDefault());
            if (quiz == null)
            {
                return Redirect("/Quiz/Quizzes");
            }
            return View(quiz);
        }

        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpGet]
        public async Task<ActionResult> GetQuiz(int id)//for debug
        {
            var quiz = await _quizService.GetByIdAsync(id);

            return Json(quiz, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "SuperAdmin")]
        [HttpGet]
        public async Task<ActionResult> QuizPassHistory(string user)
        {
            var history = await _quizService.GetHistoryOfPassQuizzes(0, 30, user);

            return View(history);
        }
    }
}

QuizSystem/Views/Quiz/QuizPage.cshtml
@model BLL.Dto.QuizDTO

@{
    ViewBag.Title = "Quiz Page";
}


<h2>Quiz: @Model.Title</h2>
<p><span class="font-weight-bold">Описание:</span> @Model.Description</p>
@if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
{
    <a class="small" href="/Edit/Quiz/@Model.Id">Редактировать</a>
}

<div class="content">
    <div id="quiz-container">
        <div class="navigation" data-quizId="@Model.Id">
            <button class="btn btn-secondary btn-sm" data-action="prev"><</button>
            <span id="current-question-indicator"></span>
            <button class="btn btn-secondary btn-sm" data-action="next">></button>
        </div>
        <div class="question-container">
            <div id="start-menu">
                <p>
                    Количество вопросов: @Model.Questions.Count
                    <br />
                    Время теста: @Model.TimeToTest сек
                </p>
                <button class="btn btn-primary" id="start-btn">Начать</button>
            </div>
            <div id="question"></div>
        </div>
        <div class="answer">
            <div class="answers" id="answers"></div>
            <button class="btn btn-outline-dark" id="btn-answer" data-action="next">Ответить</button>
            <div style="margin-left: auto;">
                <button class="btn btn-danger" id="btn-end">Завершить</button>
            </div>
        </div>
    </div>
    <div id="results"></div>
    <div style="height:100px"></div>
</div>

@section Scripts
{
    <script src="@Url.Content("~/Scripts/QuizPassMyScript.js")"></script>
}

QuizSystem/Views/Quiz/QuizPassHistory.cshtml
@model IEnumerable<BLL.Dto.QuizPassHistoryDTO>
@{
    ViewBag.Title = "History";
}
<div class="table-responsive">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mark)
            </th>
            <th>
                @Html.DisplayName("User")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuizId)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.StartTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mark)
                </td>
                <td>
                    <a href="/Account/UserInfo/@item.ApplicationUserId">@item.ApplicationUserName</a>
                </td>
                <td>
                    <a href="/Edit/Quiz/@item.QuizId">@item.QuizId</a>
                </td>
            </tr>
        }
    </table>
    <div style="height:100px"></div>
</div>

QuizSystem/Views/Quiz/Quizzes.cshtml
@model QuizSystem.Models.QuizzesViewModel
@using QuizSystem.Helpers
@{
    ViewBag.Title = "Quiz List";
}

<h1 class="text-center">Quiz List</h1>
<hr />

<div class="row">
    <div class="offset-md-4 col-md-8 col-12 mb-4">
        <form class="input-group" method="get">
            <input type="search" class="form-control rounded" name="q" placeholder="Search" value="@Request.QueryString["q"]"/>
            <button type="submit" class="btn btn-outline-primary">search</button>
        </form>
        
    </div>
   
    @if (Model.Quizzes == null || Model.Quizzes.Count() == 0)
    {
        <div class="col text-center">
            <h2 class="display-4">Список тестов пуст</h2>
            <p>
                Попробуйте найти что-то другое или возвращайтесь позже.
            </p>
        </div>
    }
    else
    {
        foreach (var item in Model.Quizzes)
        {
            <div class="col-md-4">
                <h2>@item.Title</h2>
                <p>
                    @item.Description
                </p>
                <p>@Html.ActionLink("детали \u00BB", "QuizPage", "Quiz", new { id = item.Id }, new { @class = "btn btn-secondary" })</p>
            </div>
        }
        <div class="col-12" style="min-height: 120px;">
            <hr />
            <nav aria-label="..." class="d-flex justify-content-center">
                <ul class="pagination">
                    @Html.PageLinks(Model.PageInfo, x => Url.Action("Quizzes", new { q = Request.QueryString["q"], page = x }))
                </ul>
            </nav>
        </div>
    }
</div>